package com.pawzaar.user.service;

import com.pawzaar.config.PasswordEncoderConfig;
import com.pawzaar.user.InvalidCredentialsException;
import com.pawzaar.user.InvalidRefreshTokenException;
import com.pawzaar.user.RefreshToken;
import com.pawzaar.user.Role;
import com.pawzaar.user.User;
import com.pawzaar.user.UserNotFoundException;
import com.pawzaar.user.dto.LoginRequest;
import com.pawzaar.user.dto.TokenResponse;
import com.pawzaar.user.dto.UpdateProfileRequest;
import com.pawzaar.user.dto.UserResponse;
import com.pawzaar.user.repository.RefreshTokenRepository;
import com.pawzaar.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtEncoder;
import org.springframework.security.oauth2.jwt.JwtEncoderParameters;

import java.time.Duration;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit tests for the LOGIN and REFRESH rules. This class exists because a real bug slipped through
 * here: a hand-written "dummy" hash without the {bcrypt} prefix made the encoder throw, so login
 * answered 500 instead of 401 for unknown emails. These tests now guard that path.
 *
 * <p>Note the real BCryptPasswordEncoder (not a mock): the point is to test real hashing
 * behaviour, and it costs about 100ms per encode - irrelevant in a unit test.
 */
@ExtendWith(MockitoExtension.class)
class AuthServiceTest {

    private static final String EMAIL = "ana@pawzaar.test";

    @Mock
    private UserRepository userRepository;
    @Mock
    private JwtEncoder jwtEncoder;
    @Mock
    private RefreshTokenRepository refreshTokenRepository;

    // The REAL production encoder bean (with the {bcrypt} prefix and the legacy fallback),
    // so these tests exercise the exact hashing configuration the app runs with.
    private final PasswordEncoder realEncoder = new PasswordEncoderConfig().passwordEncoder();
    private AuthService authService;

    @BeforeEach
    void setUp() {
        authService = new AuthService(
                userRepository,
                realEncoder,
                jwtEncoder,
                Duration.ofMinutes(30),
                refreshTokenRepository,
                Duration.ofDays(7));
    }

    private static User userWithHash(String hash) {
        try {
            var ctor = User.class.getDeclaredConstructor();     // protected constructor
            ctor.setAccessible(true);
            User user = ctor.newInstance();
            setField(user, "id", UUID.randomUUID());            // normally generated by Hibernate
            user.setEmail(EMAIL);
            user.setDisplayName("Ana Reyes");
            setField(user, "passwordHash", hash);               // no setter, by design
            return user;
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
    }

    private static void setField(User user, String name, Object value) {
        try {
            var field = User.class.getDeclaredField(name);
            field.setAccessible(true);
            field.set(user, value);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
    }

    private void stubToken() {
        when(jwtEncoder.encode(any(JwtEncoderParameters.class)))
                // A built Jwt needs at least one claim, otherwise it throws
                // "IllegalArgument: claims cannot be empty".
                .thenReturn(Jwt.withTokenValue("a.b.c").header("alg", "HS256").claim("sub", EMAIL).build());
    }

    // ── login ──────────────────────────────────────────────────────────────────

    @Test
    void loginWithCorrectPasswordReturnsABearerTokenAndARefreshToken() {
        when(userRepository.findByEmail(EMAIL))
                .thenReturn(Optional.of(userWithHash(realEncoder.encode("pawzaar123"))));
        stubToken();

        TokenResponse response = authService.login(new LoginRequest(EMAIL, "pawzaar123"));

        assertEquals("a.b.c", response.accessToken());
        assertEquals("Bearer", response.tokenType());
        assertEquals(1800, response.expiresInSeconds());

        // Login must ALSO mint a refresh token and persist its hash (never the raw value).
        assertNotNull(response.refreshToken());
        assertFalse(response.refreshToken().isBlank());
        verify(refreshTokenRepository).save(any(RefreshToken.class));
    }

    @Test
    void loginWithWrongPasswordFails() {
        when(userRepository.findByEmail(EMAIL))
                .thenReturn(Optional.of(userWithHash(realEncoder.encode("correct-password"))));

        assertThrows(InvalidCredentialsException.class,
                () -> authService.login(new LoginRequest(EMAIL, "wrong-password")));
    }

    @Test
    void loginWithUnknownEmailFailsTheSameWayAndDoesNotCrash() {
        // The regression test: this used to throw IllegalArgumentException -> HTTP 500.
        when(userRepository.findByEmail("ghost@pawzaar.test")).thenReturn(Optional.empty());

        InvalidCredentialsException ex = assertThrows(InvalidCredentialsException.class,
                () -> authService.login(new LoginRequest("ghost@pawzaar.test", "whatever123")));

        // Same message as a wrong password: no user enumeration.
        assertEquals("Invalid email or password", ex.getMessage());
    }

    @Test
    void loginAcceptsLegacyHashesStoredWithoutThePrefix() {
        // A hash written BEFORE the delegating encoder existed: plain BCrypt, no "{bcrypt}" prefix.
        String legacyHash = new BCryptPasswordEncoder().encode("pawzaar123");
        assertFalse(legacyHash.startsWith("{"), "this test needs an UNPREFIXED hash");

        when(userRepository.findByEmail(EMAIL)).thenReturn(Optional.of(userWithHash(legacyHash)));
        stubToken();

        // Thanks to setDefaultPasswordEncoderForMatches(...) the login still succeeds instead of
        // throwing IllegalArgumentException (which used to surface as HTTP 500).
        TokenResponse response = authService.login(new LoginRequest(EMAIL, "pawzaar123"));

        assertEquals("a.b.c", response.accessToken());
    }

    @Test
    void loginNormalisesTheEmailBeforeLookingItUp() {
        when(userRepository.findByEmail(EMAIL)).thenReturn(Optional.empty());

        assertThrows(InvalidCredentialsException.class,
                () -> authService.login(new LoginRequest("  ANA@Pawzaar.TEST  ", "whatever123")));

        // Proof: the repository was queried with the trimmed, lower-cased address.
        verify(userRepository).findByEmail(EMAIL);
    }

    // ── refresh ────────────────────────────────────────────────────────────────

    @Test
    void refreshRotatesTheTokenAndReturnsANewPair() {
        User user = userWithHash(realEncoder.encode("pawzaar123"));
        RefreshToken stored = RefreshToken.issue(
                user.getId(), "irrelevant-hash", Instant.now().plusSeconds(3600));
        when(refreshTokenRepository.findByTokenHash(anyString())).thenReturn(Optional.of(stored));
        when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
        stubToken();

        TokenResponse response = authService.refresh("some-raw-refresh-token");

        assertEquals("a.b.c", response.accessToken());
        assertNotNull(response.refreshToken());

        // ROTATION: the presented token is burned, and a brand-new one is issued.
        assertTrue(stored.isRevoked(), "the used refresh token must be revoked");
        verify(refreshTokenRepository).save(any(RefreshToken.class));
    }

    @Test
    void refreshWithUnknownTokenFails() {
        when(refreshTokenRepository.findByTokenHash(anyString())).thenReturn(Optional.empty());

        assertThrows(InvalidRefreshTokenException.class,
                () -> authService.refresh("never-issued"));
    }

    @Test
    void refreshWithRevokedTokenFails() {
        RefreshToken stored = RefreshToken.issue(UUID.randomUUID(), "h", Instant.now().plusSeconds(3600));
        stored.revoke();
        when(refreshTokenRepository.findByTokenHash(anyString())).thenReturn(Optional.of(stored));

        assertThrows(InvalidRefreshTokenException.class,
                () -> authService.refresh("already-used"));
    }

    @Test
    void refreshWithExpiredTokenFails() {
        RefreshToken stored = RefreshToken.issue(UUID.randomUUID(), "h", Instant.now().minusSeconds(1));
        when(refreshTokenRepository.findByTokenHash(anyString())).thenReturn(Optional.of(stored));

        assertThrows(InvalidRefreshTokenException.class,
                () -> authService.refresh("expired"));
    }

    // ── logout ─────────────────────────────────────────────────────────────────

    @Test
    void logoutRevokesTheToken() {
        RefreshToken stored = RefreshToken.issue(UUID.randomUUID(), "h", Instant.now().plusSeconds(3600));
        when(refreshTokenRepository.findByTokenHash(anyString())).thenReturn(Optional.of(stored));

        authService.logout("some-raw-refresh-token");

        assertTrue(stored.isRevoked());
    }

    @Test
    void logoutIsIdempotentForUnknownTokens() {
        when(refreshTokenRepository.findByTokenHash(anyString())).thenReturn(Optional.empty());

        // Must NOT throw: logging out twice, or with a stale token, is still a success.
        authService.logout("never-issued");
    }

    // ── profile (GET/PUT /api/v1/me) ───────────────────────────────────────────

    @Test
    void getProfileReturnsTheUsersProfile() {
        User user = userWithHash(realEncoder.encode("pawzaar123"));
        user.setPhone("+639171234567");
        user.setBio("Dog mom from Bulacan.");
        when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));

        UserResponse response = authService.getProfile(user.getId());

        assertEquals(user.getId(), response.id());
        assertEquals(EMAIL, response.email());
        assertEquals("Ana Reyes", response.displayName());
        assertEquals("+639171234567", response.phone());
        assertEquals("Dog mom from Bulacan.", response.bio());
    }

    @Test
    void getProfileOfAMissingUserFailsWithUserNotFound() {
        UUID userId = UUID.randomUUID();
        when(userRepository.findById(userId)).thenReturn(Optional.empty());

        assertThrows(UserNotFoundException.class, () -> authService.getProfile(userId));
    }

    @Test
    void updateProfileEditsOnlyTheEditableFields() {
        User user = userWithHash(realEncoder.encode("original-password"));
        user.setPhone("+639171234567");
        setField(user, "createdAt", Instant.parse("2026-10-01T00:00:00Z"));
        when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));
        when(userRepository.save(any(User.class))).thenAnswer(inv -> inv.getArgument(0));

        UserResponse response = authService.updateProfile(user.getId(),
                new UpdateProfileRequest("  Ana Reyes Edit  ", "", "  New bio  "));

        // Editable fields replaced (trimmed); empty phone CLEARED to null.
        assertEquals("Ana Reyes Edit", response.displayName());
        assertNull(response.phone());
        assertEquals("New bio", response.bio());
        // Identity and credentials are frozen: email, role untouched, hash never touched.
        assertEquals(EMAIL, response.email());
        assertEquals(Role.USER, response.role());
        // The change was persisted (save = UPDATE for an entity that already has an id).
        verify(userRepository).save(user);
    }

    @Test
    void updateProfileOfAMissingUserFailsWithUserNotFound() {
        UUID userId = UUID.randomUUID();
        when(userRepository.findById(userId)).thenReturn(Optional.empty());

        assertThrows(UserNotFoundException.class,
                () -> authService.updateProfile(userId, new UpdateProfileRequest("Ana", "", null)));
    }
}
