package com.pawzaar.user.service;

import com.pawzaar.config.PasswordEncoderConfig;
import com.pawzaar.user.InvalidCredentialsException;
import com.pawzaar.user.User;
import com.pawzaar.user.dto.LoginRequest;
import com.pawzaar.user.dto.LoginResponse;
import com.pawzaar.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtEncoder;
import org.springframework.security.oauth2.jwt.JwtEncoderParameters;

import java.time.Duration;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit tests for the LOGIN rules. This class exists because a real bug slipped through here:
 * a hand-written "dummy" hash without the {bcrypt} prefix made the encoder throw, so login
 * answered 500 instead of 401 for unknown emails. These tests now guard that path.
 *
 * <p>Note the real BCryptPasswordEncoder (not a mock): the point is to test real hashing
 * behaviour, and it costs about 100ms per encode - irrelevant in a unit test.
 */
@ExtendWith(MockitoExtension.class)
class AuthServiceTest {

    private static final String EMAIL = "ana@pawzaar.test";

    @Mock
    private UserRepository userRepository;
    @Mock
    private JwtEncoder jwtEncoder;

    // The REAL production encoder bean (with the {bcrypt} prefix and the legacy fallback),
    // so these tests exercise the exact hashing configuration the app runs with.
    private final PasswordEncoder realEncoder = new PasswordEncoderConfig().passwordEncoder();
    private AuthService authService;

    @BeforeEach
    void setUp() {
        authService = new AuthService(userRepository, realEncoder, jwtEncoder, Duration.ofMinutes(30));
    }

    private static User userWithHash(String hash) {
        try {
            var ctor = User.class.getDeclaredConstructor();     // protected constructor
            ctor.setAccessible(true);
            User user = ctor.newInstance();
            setField(user, "id", UUID.randomUUID());            // normally generated by Hibernate
            user.setEmail(EMAIL);
            user.setDisplayName("Ana Reyes");
            setField(user, "passwordHash", hash);               // no setter, by design
            return user;
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
    }

    private static void setField(User user, String name, Object value) {
        try {
            var field = User.class.getDeclaredField(name);
            field.setAccessible(true);
            field.set(user, value);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
    }

    private void stubToken() {
        when(jwtEncoder.encode(any(JwtEncoderParameters.class)))
                // A built Jwt needs at least one claim, otherwise it throws
                // "IllegalArgument: claims cannot be empty".
                .thenReturn(Jwt.withTokenValue("a.b.c").header("alg", "HS256").claim("sub", EMAIL).build());
    }

    @Test
    void loginWithCorrectPasswordReturnsABearerToken() {
        when(userRepository.findByEmail(EMAIL))
                .thenReturn(Optional.of(userWithHash(realEncoder.encode("pawzaar123"))));
        stubToken();

        LoginResponse response = authService.login(new LoginRequest(EMAIL, "pawzaar123"));

        assertEquals("a.b.c", response.accessToken());
        assertEquals("Bearer", response.tokenType());
        assertEquals(1800, response.expiresInSeconds());
    }

    @Test
    void loginWithWrongPasswordFails() {
        when(userRepository.findByEmail(EMAIL))
                .thenReturn(Optional.of(userWithHash(realEncoder.encode("correct-password"))));

        assertThrows(InvalidCredentialsException.class,
                () -> authService.login(new LoginRequest(EMAIL, "wrong-password")));
    }

    @Test
    void loginWithUnknownEmailFailsTheSameWayAndDoesNotCrash() {
        // The regression test: this used to throw IllegalArgumentException -> HTTP 500.
        when(userRepository.findByEmail("ghost@pawzaar.test")).thenReturn(Optional.empty());

        InvalidCredentialsException ex = assertThrows(InvalidCredentialsException.class,
                () -> authService.login(new LoginRequest("ghost@pawzaar.test", "whatever123")));

        // Same message as a wrong password: no user enumeration.
        assertEquals("Invalid email or password", ex.getMessage());
    }

    @Test
    void loginAcceptsLegacyHashesStoredWithoutThePrefix() {
        // A hash written BEFORE the delegating encoder existed: plain BCrypt, no "{bcrypt}" prefix.
        String legacyHash = new BCryptPasswordEncoder().encode("pawzaar123");
        assertFalse(legacyHash.startsWith("{"), "this test needs an UNPREFIXED hash");

        when(userRepository.findByEmail(EMAIL)).thenReturn(Optional.of(userWithHash(legacyHash)));
        stubToken();

        // Thanks to setDefaultPasswordEncoderForMatches(...) the login still succeeds instead of
        // throwing IllegalArgumentException (which used to surface as HTTP 500).
        LoginResponse response = authService.login(new LoginRequest(EMAIL, "pawzaar123"));

        assertEquals("a.b.c", response.accessToken());
    }

    @Test
    void loginNormalisesTheEmailBeforeLookingItUp() {
        when(userRepository.findByEmail(EMAIL)).thenReturn(Optional.empty());

        assertThrows(InvalidCredentialsException.class,
                () -> authService.login(new LoginRequest("  ANA@Pawzaar.TEST  ", "whatever123")));

        // Proof: the repository was queried with the trimmed, lower-cased address.
        verify(userRepository).findByEmail(EMAIL);
    }
}
