package com.pawzaar.user.dto;

// The enum we return. It is in the PARENT package (com.pawzaar.user), so it must be
// imported - sub-packages have no automatic access to their parent.
import com.pawzaar.user.Role;

import java.time.Instant;  // a moment in time (createdAt) - the modern replacement for java.util.Date
import java.util.UUID;     // the user's id, generated by Hibernate on insert

/**
 * What we RETURN to the client about a user - after registration, after login, and (since
 * Step 13b) after GET/PUT /api/v1/me.
 *
 * <p>Read the component list and notice what is MISSING: there is no passwordHash, no
 * password, nothing sensitive. That is the point. Security by omission - a field that does
 * not exist in this record cannot leak, no matter who builds the object or how it is logged.
 *
 * <p>These component names become the JSON keys automatically (id, email, displayName...).
 */
public record UserResponse(
        UUID id,
        String email,
        String displayName,
        String phone,
        Role role,
        boolean verified,
        Instant createdAt,
        String bio
) {
}